"""SQLAlchemy 2 async ORM models for every Postgres app-state table (design
spec §12): `AppUser`, `SessionRow` (table `"session"`), `LabelMeta`,
`UiPref`, `Contact`, `ImageSenderAllow`, `LoginAttempt`, `AuditLog` — plus
`Visibility`, the enum pinning `LabelMeta.visibility`'s three legal values.
Phase 1B's reading view (Task 12) adds one more: `SenderPref`, the
per-sender "Show original" memory for the dark restyle
(`mailosh.render.dark`), added by
`migrations/versions/0002_reading.py` rather than the Task 1 baseline.

Column types are deliberately restricted to the dialect-neutral set the
Task 1 brief calls for — `String`, `Text`, `Integer`, `Boolean`,
`DateTime(timezone=True)`, `LargeBinary`, `JSON` — since this same metadata
backs two different engines: `tests/conftest.py`'s in-memory aiosqlite `db`
fixture (via `Base.metadata.create_all`) for every unit test, and real
Postgres in production (via `migrations/versions/0001_foundation.py`, hand
-written to mirror this file column-for-column rather than generated by
`alembic revision --autogenerate`). A "now" default (`created_at`-shaped
columns) uses a plain Python callable (`_utcnow`, below) rather than
`server_default=func.now()` for the same cross-dialect reason: it's
computed once in Python before either dialect's INSERT is built, so it
behaves identically on both engines instead of leaning on each database's
own (subtly different — aiosqlite's `CURRENT_TIMESTAMP` isn't tz-aware the
way Postgres's `now()` is) "now" function.

No `relationship()`s are declared here — every helper in `mailosh.db.repo`
reaches related rows with an explicit `select()` instead, and no later
Task 1 consumer needs ORM-level traversal, so this stays plain columns and
constraints, nothing more.
"""

from __future__ import annotations

import logging
from datetime import UTC, datetime
from enum import StrEnum

from sqlalchemy import JSON, Boolean, DateTime, ForeignKey, Integer, LargeBinary, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from mailosh.db.base import Base

_log = logging.getLogger(__name__)


def _utcnow() -> datetime:
    return datetime.now(UTC)


class AppUser(Base):
    """One row per webmail login identity — keyed to the Stalwart account
    it authenticates as (`stalwart_username`), not to the app's own concept
    of an id shown anywhere else.
    """

    __tablename__ = "app_user"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    stalwart_username: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    email: Mapped[str] = mapped_column(String(255), nullable=False)
    display_name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    is_admin: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)


class SessionRow(Base):
    """A logged-in browser session (design spec §9) — table name `"session"`,
    not the class name, per the Task 1 brief. `api_key_secret_enc` holds the
    per-session Stalwart API key, Fernet-encrypted (`mailosh.security.crypto`,
    Task 3) with a key derived from `Settings.secret_key`; this table never
    stores a plaintext credential.
    """

    __tablename__ = "session"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    user_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("app_user.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    remember: Mapped[bool] = mapped_column(Boolean, nullable=False)
    user_agent: Mapped[str | None] = mapped_column(Text, nullable=True)
    ip: Mapped[str | None] = mapped_column(String(64), nullable=True)
    api_key_id: Mapped[str | None] = mapped_column(String(64), nullable=True)
    api_key_secret_enc: Mapped[bytes] = mapped_column(LargeBinary, nullable=False)
    csrf_token: Mapped[str] = mapped_column(String(64), nullable=False)


class Visibility(StrEnum):
    """The complete vocabulary of `LabelMeta.visibility` — spec §5.2's label
    hover menu offers exactly "show / hide / show if unread", and these are
    the three tokens that encode it on the wire and in the column.

    Defined here, next to the column itself, so there is exactly one place
    the strings exist: `mailosh.services.mailbox_tree` reads them, and
    whichever later task ships the label-visibility control (1D) must write
    them. Before this enum they were bare literals living only inside
    `mailbox_tree` and its tests, and `visibility` is an unconstrained
    `String(16)` with no CHECK or native enum in
    `migrations/versions/0001_foundation.py` — so a writer that guessed
    `"hidden"` or `"show-if-unread"` would have been accepted by the
    database and then silently read as "show", leaving a label the user had
    explicitly hidden fully visible. `parse` below is the other half of
    closing that gap.

    A plain `StrEnum` (not `sa.Enum`) deliberately: the column stays a
    dialect-neutral `String(16)` matching the hand-written migration
    column-for-column, per this module's own "restricted, dialect-neutral
    column types" rule. Every value is <= 16 characters.
    """

    SHOW = "show"
    HIDE = "hide"
    SHOW_IF_UNREAD = "show_if_unread"

    @classmethod
    def parse(cls, raw: str | None) -> "Visibility":
        """Coerce a stored `visibility` string into a `Visibility`.

        `None` (no `LabelMeta` row at all) is the documented default,
        `SHOW`. An *unrecognised* non-null token is a bug in whatever wrote
        it, and this resolves it to `HIDE` — the conservative direction —
        while logging a warning naming the offending value.

        The choice matters, so it is stated explicitly: the two failure
        directions are not symmetric. Resolving an unintelligible
        preference to `SHOW` can contradict an explicit hide and surface a
        label (and its chips) the user deliberately suppressed, silently
        and with no signal anywhere. Resolving it to `HIDE` can at worst
        make a label temporarily disappear — visible to the user, obviously
        wrong, recoverable by re-setting it, and loud in the logs. Raising
        was the third option and was rejected: one malformed row should not
        take down the entire nav, and therefore the entire mail UI, for a
        cosmetic preference.
        """
        if raw is None:
            return cls.SHOW
        try:
            return cls(raw)
        except ValueError:
            _log.warning(
                "unrecognised LabelMeta.visibility %r; treating as %r (valid values: %s)",
                raw,
                cls.HIDE.value,
                ", ".join(v.value for v in cls),
            )
            return cls.HIDE


class LabelMeta(Base):
    """Per-user display metadata for a JMAP mailbox acting as a label (design
    spec §10) — colour/visibility/pinned order live here; the label itself
    (name, nesting) stays a JMAP `Mailbox`, never duplicated into Postgres.
    """

    __tablename__ = "label_meta"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("app_user.id"), primary_key=True)
    account_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    mailbox_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    color: Mapped[str | None] = mapped_column(String(32), nullable=True)
    visibility: Mapped[str] = mapped_column(
        String(16), nullable=False, default=Visibility.SHOW.value
    )
    sort_order: Mapped[int | None] = mapped_column(Integer, nullable=True)


class UiPref(Base):
    """One row per user: Appearance/Reading/Compose quick-settings (design
    spec §10) — `mailosh.db.repo.get_prefs` creates this row with every
    column at its default the first time a user is looked up.
    """

    __tablename__ = "ui_pref"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("app_user.id"), primary_key=True)
    theme: Mapped[str] = mapped_column(String(16), nullable=False, default="system")
    density: Mapped[str] = mapped_column(String(16), nullable=False, default="comfortable")
    reading_pane: Mapped[str] = mapped_column(String(16), nullable=False, default="none")
    conversation_view: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    mark_read_delay: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    auto_advance: Mapped[str] = mapped_column(String(16), nullable=False, default="older")
    undo_send_seconds: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    default_reply: Mapped[str] = mapped_column(String(16), nullable=False, default="reply")
    remote_images: Mapped[str] = mapped_column(String(16), nullable=False, default="ask")
    dark_restyle: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    shortcuts: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    font_size: Mapped[str] = mapped_column(String(8), nullable=False, default="md")


class Signature(Base):
    """One saved signature per *identity* (design spec §10's Compose page).

    Keyed by `(user_id, account_id, identity_id)` rather than by user alone
    because "send as" is per address: the point of the setting is that mail
    from `ada@work` can sign off differently from mail from `ada@home`, and
    a single per-user row could not say that. `account_id` rides along for
    the same reason `LabelMeta` carries one — an identity id is only unique
    inside its own JMAP account, so a user who ever reaches a second account
    must not have its identities collide with the first's.

    `html` is stored **already sanitised**, through
    `mailosh.render.html_sanitize.sanitize_email_html` — the same nh3
    allow-list the reading pane runs every stranger's mail through. It is
    written by the settings page and read back into an outgoing body, so
    it is markup that leaves this deployment; storing what was typed and
    cleaning it later would leave exactly one path (a future reader of this
    table that forgot) between a `<script>` and somebody's mailbox. Empty
    string means "no signature", the value a cleared textarea saves, so
    nothing here has to distinguish a blank row from a missing one.
    """

    __tablename__ = "signature"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("app_user.id"), primary_key=True)
    account_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    identity_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    html: Mapped[str] = mapped_column(Text, nullable=False, default="")
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )


class Contact(Base):
    """A harvested "people you've emailed" row (compose autocomplete, a later
    task) — `count`/`last_seen_at` let that later task rank/prune entries.
    """

    __tablename__ = "contact"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("app_user.id"), primary_key=True)
    email: Mapped[str] = mapped_column(String(255), primary_key=True)
    name: Mapped[str | None] = mapped_column(String(255), nullable=True)
    last_seen_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    count: Mapped[int] = mapped_column(Integer, nullable=False, default=1)


class ImageSenderAllow(Base):
    """A per-user "always load remote images from this sender" allow-list
    entry (design spec §10's `remote_images` policy, a later task).
    """

    __tablename__ = "image_sender_allow"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("app_user.id"), primary_key=True)
    sender_email: Mapped[str] = mapped_column(String(255), primary_key=True)


class SenderPref(Base):
    """A per-sender "Show original" override for the dark restyle
    (`mailosh.render.dark.restyle_mode`, design spec §7, Task 12) — the
    row `mailosh.db.repo.set_sender_restyle` writes the first time a reader
    clicks "Show original" on a message from `sender_email`, and
    `repo.sender_pref` reads back on every later message from that same
    sender, in that same user's mail.

    `dark_restyle` is nullable and three-valued on purpose, same shape as
    `LabelMeta.visibility`'s "no row at all" default: `None` (the value a
    freshly-created row starts at, and the only value today's one caller —
    "Show original" — ever writes besides `False`) means no override,
    `False` means "never restyle this sender again", and `True` is left
    available for a future "always restyle, even declared/dark" control
    without a schema change. Unlike `UiPref`, a `SenderPref` row is never
    auto-created on lookup (`repo.sender_pref` returns `None`, it does not
    invent a row) — "no preference recorded yet" and "a row saying so"
    must stay distinguishable only in the sense that both mean the same
    thing to a caller, never in the sense that one is silently upgraded to
    the other by the read path.
    """

    __tablename__ = "sender_pref"

    user_id: Mapped[int] = mapped_column(Integer, ForeignKey("app_user.id"), primary_key=True)
    sender_email: Mapped[str] = mapped_column(String(255), primary_key=True)
    dark_restyle: Mapped[bool | None] = mapped_column(Boolean, nullable=True, default=None)


class LoginAttempt(Base):
    """A rate-limit counter keyed by an opaque `key` (e.g. `"ip:1.2.3.4"` or
    `"account:demo@mailosh.test"` — `mailosh.security.ratelimit`, Task 5,
    owns exactly what a key looks like; this table just stores the counter).
    """

    __tablename__ = "login_attempt"

    key: Mapped[str] = mapped_column(String(255), primary_key=True)
    failures: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    window_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    locked_until: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)


class AuditLog(Base):
    """An append-only security/activity trail row (login success/failure,
    logout, etc. — design spec §9) — `mailosh.db.repo.audit` appends these;
    nothing in this task or a later one ever updates or deletes a row here.
    """

    __tablename__ = "audit_log"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    user_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("app_user.id"), nullable=True)
    action: Mapped[str] = mapped_column(String(64), nullable=False)
    detail: Mapped[dict | None] = mapped_column(JSON, nullable=True)
    ip: Mapped[str | None] = mapped_column(String(64), nullable=True)
    at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=_utcnow)
